module.exports = {
  elements: [
    {
      name: 'Ninguno',
      summary: 'La matriz empezará con el elemento 1, Hidrógeno'
    },
    {
      name: 'Hidrógeno',
      appearance: 'Gas incoloro',
      atomic_mass: 1.008,
      boil: 20.271,
      category: 'no metal',
      color: null,
      density: 0.08988,
      discovered_by: 'Henry Cavendish',
      melt: 13.99,
      molar_heat: 28.836,
      named_by: 'Antoine Lavoisier',
      number: 1,
      period: 1,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Hidr%C3%B3geno',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Hydrogen_Spectra.jpg',
      summary:
        'El hidrógeno es el elemento químico de número atómico 1, representado por el símbolo H. Con una masa atómica de 1,00797, ​ es el más ligero de la tabla periódica de los elementos. Por lo general, se presenta en su forma molecular, formando el gas diatómico H₂ en condiciones normales.',
      symbol: 'H',
      xpos: 1,
      ypos: 1,
      shells: [1]
    },
    {
      name: 'Helio',
      appearance:
        'Incoloro',
      atomic_mass: 4.0026022,
      boil: 4.222,
      category: 'gas noble',
      color: null,
      density: 0.1786,
      discovered_by: 'Pierre Janssen',
      melt: 0.95,
      molar_heat: null,
      named_by: null,
      number: 2,
      period: 1,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Helio',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Helium_spectrum.jpg',
      summary:
        'Elemento químico de número atómico 2, masa atómica 4,003 y símbolo He ; es un gas noble incoloro, inodoro, inerte y muy ligero (el más ligero después del hidrógeno), es muy abundante en el universo y se utiliza para elevar globos, en investigación de cohetes, en láser, como parte de la atmósfera sintética de los buceadores y, en forma líquida, como refrigerante.',
      symbol: 'He',
      xpos: 18,
      ypos: 1,
      shells: [2]
    },
    {
      name: 'Litio',
      appearance: 'Blanco plateado/gris',
      atomic_mass: 6.94,
      boil: 1603,
      category: 'metal alcalino',
      color: null,
      density: 0.534,
      discovered_by: 'Johan August Arfwedson',
      melt: 453.65,
      molar_heat: 24.86,
      named_by: null,
      number: 3,
      period: 2,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Litio',
      spectral_img: null,
      summary:
        'El litio (en griego: λιθίον ‘piedrecita’)1​ es un elemento químico de símbolo Li y número atómico 3. En la tabla periódica, se encuentra en el grupo 1, entre los elementos alcalinos. En su forma pura, es un metal blando, de color blanco plata, que se oxida rápidamente en aire o agua. Su densidad es la mitad de la del agua, siendo el metal y elemento sólido más ligero.',
      symbol: 'Li',
      xpos: 1,
      ypos: 2,
      shells: [2, 1]
    },
    {
      name: 'Berilio',
      appearance: 'Blanco-gris metálico',
      atomic_mass: 9.01218315,
      boil: 2742,
      category: 'metal alcalinotérreo',
      color: null,
      density: 1.85,
      discovered_by: 'Louis Nicolas Vauquelin',
      melt: 1560,
      molar_heat: 16.443,
      named_by: null,
      number: 4,
      period: 2,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Berilio',
      spectral_img: null,
      summary:
        'El berilio es un elemento químico de símbolo Be y número atómico 4. Es un elemento Alcalinotérreo bivalente, tóxico, de color gris, duro, ligero y quebradizo. Se emplea principalmente como endurecedor en aleaciones, especialmente de cobre.',
      symbol: 'Be',
      xpos: 2,
      ypos: 2,
      shells: [2, 2]
    },
    {
      name: 'Boro',
      appearance: 'Negro/gris',
      atomic_mass: 10.81,
      boil: 4200,
      category: 'metaloide',
      color: null,
      density: 2.08,
      discovered_by: 'Joseph Louis Gay-Lussac',
      melt: 2349,
      molar_heat: 11.087,
      named_by: null,
      number: 5,
      period: 2,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Boro',
      spectral_img: null,
      summary:
        "El boro es un elemento químico de la tabla periódica de los elementos que tiene el símbolo B1​ y número atómico 5, su masa es de 10,811. Es un elemento metaloide, semiconductor, trivalente que existe abundantemente en el mineral bórax. Hay dos alótropos del boro; el boro amorfo es un polvo marrón, pero el boro metálico es negro.",
      symbol: 'B',
      xpos: 13,
      ypos: 2,
      shells: [2, 3]
    },
    {
      name: 'Carbón',
      appearance: 'Negro',
      atomic_mass: 12.011,
      boil: null,
      category: 'no metal poliatómico',
      color: null,
      density: 1.821,
      discovered_by: 'Ancient Egypt',
      melt: null,
      molar_heat: 8.517,
      named_by: null,
      number: 6,
      period: 2,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Carb%C3%B3n',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Carbon_Spectra.jpg',
      summary:
        'El carbón o carbón mineral es una roca sedimentaria organógena de color negro, muy rica en carbono y con cantidades variables de otros elementos, principalmente hidrógeno, azufre, oxígeno y nitrógeno. Principalmente es utilizada como combustible fósil.',
      symbol: 'C',
      xpos: 14,
      ypos: 2,
      shells: [2, 4]
    },
    {
      name: 'Nitrógeno',
      appearance: 'Gas Incoloro, líquido o sólido',
      atomic_mass: 14.007,
      boil: 77.355,
      category: 'no metal',
      color: null,
      density: 1.251,
      discovered_by: 'Daniel Rutherford',
      melt: 63.15,
      molar_heat: null,
      named_by: 'Jean-Antoine Chaptal',
      number: 7,
      period: 2,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Nitr%C3%B3geno',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Nitrogen_Spectra.jpg',
      summary:
        'El nitrógeno es un elemento químico de número atómico 7, símbolo N, su masa atómica es de 14,0067 y que en condiciones normales forma un gas diatómico (nitrógeno diatómico o molecular) que constituye del orden del 78 % del aire atmosférico. Antiguamente era llamado ázoe (símbolo Az).',
      symbol: 'N',
      xpos: 15,
      ypos: 2,
      shells: [2, 5]
    },
    {
      name: 'Oxígeno',
      appearance: 'Sin aparariencia',
      atomic_mass: 15.999,
      boil: 90.188,
      category: 'no metal',
      color: null,
      density: 1.429,
      discovered_by: 'Carl Wilhelm Scheele',
      melt: 54.36,
      molar_heat: null,
      named_by: 'Antoine Lavoisier',
      number: 8,
      period: 2,
      phase: 'Gas',
      source: 'https://en.wikipedia.org/wiki/Oxygen',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Oxygen_spectre.jpg',
      summary:
        'El oxígeno es un elemento químico de número atómico 8 y representado por el símbolo O. Su nombre proviene de las raíces griegas ὀξύς (oxys) («ácido», literalmente «punzante», en referencia al sabor de los ácidos) y –γόνος (-gonos) («productor», literalmente «engendrador»; es decir, "productor de ácidos"), porque en la época en que se le dio esta denominación se creía, incorrectamente, que todos los ácidos requerían oxígeno para su composición.',
      symbol: 'O',
      xpos: 16,
      ypos: 2,
      shells: [2, 6]
    },
    {
      name: 'Flúor',
      appearance: 'gas pálido verde-amarillo',
      atomic_mass: 18.9984031636,
      boil: 85.03,
      category: 'no metal',
      color: null,
      density: 1.696,
      discovered_by: 'Andr\u00e9-Marie Amp\u00e8re',
      melt: 53.48,
      molar_heat: null,
      named_by: 'Humphry Davy',
      number: 9,
      period: 2,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Fl%C3%BAor',
      spectral_img: null,
      summary:
        'El flúor es el elemento químico de número atómico 9 situado en el grupo de los halógenos (grupo 17) de la tabla periódica de los elementos. Su símbolo es F.',
      symbol: 'F',
      xpos: 17,
      ypos: 2,
      shells: [2, 7]
    },
    {
      name: 'Neón',
      appearance:
        'colorless gas exhibiting an orange-red glow when placed in a high voltage electric field',
      atomic_mass: 20.17976,
      boil: 27.104,
      category: 'gas noble',
      color: null,
      density: 0.9002,
      discovered_by: 'Morris Travers',
      melt: 24.56,
      molar_heat: null,
      named_by: null,
      number: 10,
      period: 2,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Ne%C3%B3n',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Neon_spectra.jpg',
      summary:
        'El neón es un elemento químico de número atómico 10 y símbolo Ne. Es un gas noble, incoloro, prácticamente inerte, presente en trazas en el aire, pero muy abundante en el universo, que proporciona un tono rojizo característico a la luz de las lámparas fluorescentes en las que se emplea.',
      symbol: 'Ne',
      xpos: 18,
      ypos: 2,
      shells: [2, 8]
    },
    {
      name: 'Sodio',
      appearance: 'blanco plateado',
      atomic_mass: 22.989769282,
      boil: 1156.09,
      category: 'metal alcalino',
      color: null,
      density: 0.968,
      discovered_by: 'Humphry Davy',
      melt: 370.944,
      molar_heat: 28.23,
      named_by: null,
      number: 11,
      period: 3,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Sodio',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Sodium_Spectra.jpg',
      summary:
        'El sodio es un elemento químico de símbolo Na con número atómico 11 que fue descubierto en 1807. Es un metal alcalino blando, untuoso, de color plateado, muy abundante en la naturaleza, encontrándose en la sal marina . Es muy reactivo, arde con llama amarilla, se oxida en presencia de oxígeno y reacciona violentamente con el agua.',
      symbol: 'Na',
      xpos: 1,
      ypos: 3,
      shells: [2, 8, 1]
    },
    {
      name: 'Magnesio',
      appearance: 'Blanco plateado',
      atomic_mass: 24.305,
      boil: 1363,
      category: 'metal alcalinotérreo',
      color: null,
      density: 1.738,
      discovered_by: 'Joseph Black',
      melt: 923,
      molar_heat: 24.869,
      named_by: null,
      number: 12,
      period: 3,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Magnesio',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Magnesium_Spectra.jpg',
      summary:
        'El magnesio es el elemento químico de símbolo Mg y número atómico 12. Su masa atómica es de 24,305 u. Es el octavo elemento en abundancia en el orden del  % de la corteza terrestre y el tercero más abundante disuelto en el agua de mar.',
      symbol: 'Mg',
      xpos: 2,
      ypos: 3,
      shells: [2, 8, 2]
    },
    {
      name: 'Aluminio',
      appearance: 'Plateado',
      atomic_mass: 26.98153857,
      boil: 2743,
      category: 'metal de post transición',
      color: null,
      density: 2.7,
      discovered_by: null,
      melt: 933.47,
      molar_heat: 24.2,
      named_by: 'Humphry Davy',
      number: 13,
      period: 3,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Aluminio',
      spectral_img: null,
      summary:
        "El aluminio es un elemento químico, de símbolo Al y número atómico 13. Se trata de un metal no ferromagnético. Es el tercer elemento más común encontrado en la corteza terrestre. Los compuestos de aluminio forman el 8 % de la corteza de la tierra y se encuentran presentes en la mayoría de las rocas, de la vegetación y de los animales.",
      symbol: 'Al',
      xpos: 13,
      ypos: 3,
      shells: [2, 8, 3]
    },
    {
      name: 'Silicio',
      appearance: '	Gris oscuro azulado',
      atomic_mass: 28.085,
      boil: 3538,
      category: 'metaloide',
      color: null,
      density: 2.329,
      discovered_by: 'J\u00f6ns Jacob Berzelius',
      melt: 1687,
      molar_heat: 19.789,
      named_by: 'Thomas Thomson (chemist)',
      number: 14,
      period: 3,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Silicio',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Silicon_Spectra.jpg',
      summary:
        "El silicio (del latín: sílex) es un elemento químico metaloide, número atómico 14 y situado en el grupo 14 de la tabla periódica de los elementos de símbolo Si. Es el segundo elemento más abundante en la corteza terrestre (25,7 % en peso) después del oxígeno.",
      symbol: 'Si',
      xpos: 14,
      ypos: 3,
      shells: [2, 8, 4]
    },
    {
      name: 'Fósforo',
      appearance: 'Existen dos alótropos: fósforo rojo y fósforo blanco.',
      atomic_mass: 30.9737619985,
      boil: null,
      category: 'no metal poliatómico',
      color: null,
      density: 1.823,
      discovered_by: 'Hennig Brand',
      melt: null,
      molar_heat: 23.824,
      named_by: null,
      number: 15,
      period: 3,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/F%C3%B3sforo',
      spectral_img: null,
      summary:
        'El fósforo es un elemento químico de número atómico 15 y símbolo P. El nombre proviene del griego φώς [fos] ‘luz’ y φόρος [foros] ‘portador’. Es un no metal multivalente perteneciente al grupo del nitrógeno (Grupo 15 (VA): nitrogenoideos) que se encuentra en la naturaleza combinado en fosfatos inorgánicos y en organismos vivos pero nunca en estado fundamental.',
      symbol: 'P',
      xpos: 15,
      ypos: 3,
      shells: [2, 8, 5]
    },
    {
      name: 'Azufre',
      appearance: 'amarillo limón',
      atomic_mass: 32.06,
      boil: 717.8,
      category: 'no metal poliatómico',
      color: null,
      density: 2.07,
      discovered_by: 'Ancient china',
      melt: 388.36,
      molar_heat: 22.75,
      named_by: null,
      number: 16,
      period: 3,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Azufre',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Sulfur_Spectrum.jpg',
      summary:
        'El azufre es un elemento químico de número atómico 16 y símbolo S (del latín sulphur). Es un no metal abundante con un color amarillo característico.​ Dicho elemento es generado en estrellas masivas en las que predominan temperaturas que provocan la fusión entre un núcleo de silicio y otro de helio en un proceso denominado nucleosíntesis de supernovas.',
      symbol: 'S',
      xpos: 16,
      ypos: 3,
      shells: [2, 8, 6]
    },
    {
      name: 'Cloro',
      appearance: 'Gas amarillo verdoso',
      atomic_mass: 35.45,
      boil: 239.11,
      category: 'no metal',
      color: null,
      density: 3.2,
      discovered_by: 'Carl Wilhelm Scheele',
      melt: 171.6,
      molar_heat: null,
      named_by: null,
      number: 17,
      period: 3,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Cloro',
      spectral_img:
        'https://en.wikipedia.org/wiki/File:Chlorine_spectrum_visible.png',
      summary:
        'El cloro es un elemento químico de número atómico 17 situado en el grupo de los halógenos (grupo VIIA) de la tabla periódica de los elementos. Su símbolo es Cl. En condiciones normales y en estado puro forma dicloro: un gas tóxico amarillo-verdoso formado por moléculas diatómicas (Cl2) unas 2,5 veces más pesado que el aire, de olor desagradable y tóxico.',
      symbol: 'Cl',
      xpos: 17,
      ypos: 3,
      shells: [2, 8, 7]
    },
    {
      name: 'Argón',
      appearance:
        'Incoloro',
      atomic_mass: 39.9481,
      boil: 87.302,
      category: 'gas noble',
      color: null,
      density: 1.784,
      discovered_by: 'Lord Rayleigh',
      melt: 83.81,
      molar_heat: null,
      named_by: null,
      number: 18,
      period: 3,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Arg%C3%B3n',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Argon_Spectrum.png',
      summary:
        "El argón es un elemento químico de número atómico 18 y símbolo Ar. Es el tercero de los gases nobles, incoloro e inerte como ellos, constituye el 0,934 % del aire seco. Su nombre proviene del griego ἀργός [argos], que significa inactivo (debido a que no reacciona).",
      symbol: 'Ar',
      xpos: 18,
      ypos: 3,
      shells: [2, 8, 8]
    },
    {
      name: 'Potasio',
      appearance: 'Blanco plateado',
      atomic_mass: 39.09831,
      boil: 1032,
      category: 'metal alcalino',
      color: null,
      density: 0.862,
      discovered_by: 'Humphry Davy',
      melt: 336.7,
      molar_heat: 29.6,
      named_by: null,
      number: 19,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Potasio',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Potassium_Spectrum.jpg',
      summary:
        'El potasio es un elemento químico de la tabla periódica cuyo símbolo químico es K (del latín Kalium y del árabe. القلية, DMG al-qalya, "ceniza de plantas"), cuyo número atómico es 19. Es un metal alcalino de color blanco-plateado, que abunda en la naturaleza en los elementos relacionados con el agua salada y otros minerales.',
      symbol: 'K',
      xpos: 1,
      ypos: 4,
      shells: [2, 8, 8, 1]
    },
    {
      name: 'Calcio',
      appearance: 'Blanco plateado',
      atomic_mass: 40.0784,
      boil: 1757,
      category: 'metal alcalinotérreo',
      color: null,
      density: 1.55,
      discovered_by: 'Humphry Davy',
      melt: 1115,
      molar_heat: 25.929,
      named_by: null,
      number: 20,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Calcio',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Calcium_Spectrum.png',
      summary:
        "El calcio (del latín calx, calis, cal) es un elemento químico, de símbolo Ca y de número atómico 20. Su masa atómica es 40,078 u. El calcio es un metal blando, grisáceo, y es el quinto más abundante en masa de la corteza terrestre.",
      symbol: 'Ca',
      xpos: 2,
      ypos: 4,
      shells: [2, 8, 8, 2]
    },
    {
      name: 'Escandio',
      appearance: 'Blanco plateado',
      atomic_mass: 44.9559085,
      boil: 3109,
      category: 'metal de transición',
      color: null,
      density: 2.985,
      discovered_by: 'Lars Fredrik Nilson',
      melt: 1814,
      molar_heat: 25.52,
      named_by: null,
      number: 21,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Escandio',
      spectral_img: null,
      summary:
        'El escandio es un elemento químico de la tabla periódica cuyo símbolo es Sc y su número atómico es 21. Es un metal de transición que se encuentra en minerales de Escandinavia y que se clasifica con frecuencia entre los lantánidos por sus similitudes con ellos.',
      symbol: 'Sc',
      xpos: 3,
      ypos: 4,
      shells: [2, 8, 9, 2]
    },
    {
      name: 'Titanio',
      appearance: 'Titanio',
      atomic_mass: 47.8671,
      boil: 3560,
      category: 'metal de transición',
      color: null,
      density: 4.506,
      discovered_by: 'William Gregor',
      melt: 1941,
      molar_heat: 25.06,
      named_by: 'Martin Heinrich Klaproth',
      number: 22,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Titanio',
      spectral_img: null,
      summary:
        'El titanio es un elemento químico de símbolo Ti y número atómico 22 que se sitúa en el grupo 4 de la tabla periódica de los elementos. Es un metal de transición de color gris, baja densidad y gran dureza. Es muy resistente a la corrosión por agua del mar, agua regia y cloro.',
      symbol: 'Ti',
      xpos: 4,
      ypos: 4,
      shells: [2, 8, 10, 2]
    },
    {
      name: 'Vanadio',
      appearance: 'Blanco agrisado',
      atomic_mass: 50.94151,
      boil: 3680,
      category: 'metal de transición',
      color: null,
      density: 6.0,
      discovered_by: 'Andr\u00e9s Manuel del R\u00edo',
      melt: 2183,
      molar_heat: 24.89,
      named_by: 'Isotopes of vanadium',
      number: 23,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Vanadio',
      spectral_img: null,
      summary:
        'El vanadio es un elemento químico de número atómico 23 situado en el grupo 5 de la tabla periódica de los elementos. Su símbolo es V. Es un metal dúctil, pero duro, poco abundante. Se encuentra en distintos minerales y se emplea principalmente en algunas aleaciones. El nombre procede de la diosa de la belleza Vanadis en la mitología nórdica.',
      symbol: 'V',
      xpos: 5,
      ypos: 4,
      shells: [2, 8, 11, 2]
    },
    {
      name: 'Cromo',
      appearance: 'Plateado metálico',
      atomic_mass: 51.99616,
      boil: 2944,
      category: 'metal de transición',
      color: null,
      density: 7.19,
      discovered_by: 'Louis Nicolas Vauquelin',
      melt: 2180,
      molar_heat: 23.35,
      named_by: null,
      number: 24,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Cromo',
      spectral_img: null,
      summary:
        'El cromo es un elemento químico de número atómico 24 que se encuentra en el grupo 6 de la tabla periódica de los elementos. Su símbolo es Cr. Es un metal que se emplea especialmente en metalurgia. Su nombre cromo (derivado del griego chroma, ‘color’) se debe a los distintos colores que presentan sus compuestos.',
      symbol: 'Cr',
      xpos: 6,
      ypos: 4,
      shells: [2, 8, 13, 1]
    },
    {
      name: 'Manganeso',
      appearance: 'Plateado metálico',
      atomic_mass: 54.9380443,
      boil: 2334,
      category: 'metal de transición',
      color: null,
      density: 7.21,
      discovered_by: 'Torbern Olof Bergman',
      melt: 1519,
      molar_heat: 26.32,
      named_by: null,
      number: 25,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Manganeso',
      spectral_img: null,
      summary:
        'El manganeso es un elemento químico de número atómico 25 situado en el grupo 7 de la tabla periódica de los elementos y se simboliza como Mn. Se encuentra como elemento libre en la naturaleza, a menudo en combinación con el hierro y en muchos minerales. Como elemento libre, el manganeso es un metal con aleación de metales industriales con importantes usos, sobre todo en los aceros inoxidables.',
      symbol: 'Mn',
      xpos: 7,
      ypos: 4,
      shells: [2, 8, 13, 2]
    },
    {
      name: 'Hierro',
      appearance: 'Metálico brillante con un tono gris',
      atomic_mass: 55.8452,
      boil: 3134,
      category: 'metal de transición',
      color: null,
      density: 7.874,
      discovered_by: '5000 BC',
      melt: 1811,
      molar_heat: 25.1,
      named_by: null,
      number: 26,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Hierro',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Iron_Spectrum.jpg',
      summary:
        "El hierro​ es un elemento químico de número atómico 26 situado en el grupo 8, periodo 4 de la tabla periódica de los elementos. Su símbolo es Fe (del latín fĕrrum)1​ y tiene una masa atómica de 55,847 u.",
      symbol: 'Fe',
      xpos: 8,
      ypos: 4,
      shells: [2, 8, 14, 2]
    },
    {
      name: 'Cobalto',
      appearance: 'Metálico con tono gris',
      atomic_mass: 58.9331944,
      boil: 3200,
      category: 'metal de transición',
      color: 'metallic gray',
      density: 8.9,
      discovered_by: 'Georg Brandt',
      melt: 1768,
      molar_heat: 24.81,
      named_by: null,
      number: 27,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Cobalto',
      spectral_img: null,
      summary:
        "El cobalto (del alemán kobalt, voz derivada de kobolds, los Duendes que, según los mineros de Sajonia de la Edad Media, eran espíritus de la tierra que tenían embrujado el mineral, por lo que, aunque parecía mena de cobre, no producía este elemento con el tratamiento habitual​) es un elemento químico de número atómico 27 y símbolo Co situado en el grupo 9 de la tabla periódica de los elementos.",
      symbol: 'Co',
      xpos: 9,
      ypos: 4,
      shells: [2, 8, 15, 2]
    },
    {
      name: 'Níquel',
      appearance: 'Lustroso metálico',
      atomic_mass: 58.69344,
      boil: 3003,
      category: 'metal de transición',
      color: null,
      density: 8.908,
      discovered_by: 'Axel Fredrik Cronstedt',
      melt: 1728,
      molar_heat: 26.07,
      named_by: null,
      number: 28,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/N%C3%ADquel',
      spectral_img: null,
      summary:
        'El níquel es un elemento químico cuyo número atómico es 28 y su símbolo es Ni, situado en el grupo 10 de la tabla periódica de los elementos.',
      symbol: 'Ni',
      xpos: 10,
      ypos: 4,
      shells: [2, 8, 16, 2]
    },
    {
      name: 'Cobre',
      appearance: 'Metálico, cobrizo',
      atomic_mass: 63.5463,
      boil: 2835,
      category: 'metal de transición',
      color: null,
      density: 8.96,
      discovered_by: 'Middle East',
      melt: 1357.77,
      molar_heat: 24.44,
      named_by: null,
      number: 29,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Cobre',
      spectral_img: null,
      summary:
        'El cobre (del latín cuprum, y este del griego kypros, Chipre), cuyo símbolo es Cu, es el elemento químico de número atómico 29. Se trata de un metal de transición de color cobrizo, es decir, rojizo anaranjado de brillo metálico que, junto con la plata, el oro y el roentgenio forma parte de la llamada familia del cobre, se caracteriza por ser uno de los mejores conductores de electricidad (el segundo después de la plata).',
      symbol: 'Cu',
      xpos: 11,
      ypos: 4,
      shells: [2, 8, 18, 1]
    },
    {
      name: 'Zinc',
      appearance: 'Gris, en algunos casos, azulado',
      atomic_mass: 65.382,
      boil: 1180,
      category: 'metal de transición',
      color: null,
      density: 7.14,
      discovered_by: 'India',
      melt: 692.68,
      molar_heat: 25.47,
      named_by: null,
      number: 30,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Zinc',
      spectral_img: null,
      summary:
        'El zinc​ (del alemán Zink), también escrito cinc, es un elemento químico esencial de número atómico 30 y símbolo Zn, situado en el grupo 12 de la tabla periódica de los elementos.',
      symbol: 'Zn',
      xpos: 12,
      ypos: 4,
      shells: [2, 8, 18, 2]
    },
    {
      name: 'Galio',
      appearance: 'Blanco plateado',
      atomic_mass: 69.7231,
      boil: 2673,
      category: 'metal de post transición',
      color: null,
      density: 5.91,
      discovered_by: 'Lecoq de Boisbaudran',
      melt: 302.9146,
      molar_heat: 25.86,
      named_by: null,
      number: 31,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Galio',
      spectral_img: null,
      summary:
        'El galio es un elemento químico de la tabla periódica de número atómico 31 y símbolo Ga. Descubierto por el químico francés Paul Émile Lecoq de Boisbaudran en 1875,​ El galio está en el grupo 13 de la tabla periódica y es similar a los otros metales del grupo como el aluminio, el indio y el talio.',
      symbol: 'Ga',
      xpos: 13,
      ypos: 4,
      shells: [2, 8, 18, 3]
    },
    {
      name: 'Germanio',
      appearance: 'Blanco grisáceo',
      atomic_mass: 72.6308,
      boil: 3106,
      category: 'metaloide',
      color: null,
      density: 5.323,
      discovered_by: 'Clemens Winkler',
      melt: 1211.4,
      molar_heat: 23.222,
      named_by: null,
      number: 32,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Germanio',
      spectral_img: null,
      summary:
        'El germanio (latín: Germanium) es un elemento químico con número atómico 32, y símbolo Ge perteneciente al período 4 de la tabla periódica de los elementos.',
      symbol: 'Ge',
      xpos: 14,
      ypos: 4,
      shells: [2, 8, 18, 4]
    },
    {
      name: 'Arsénico',
      appearance: 'Gris metálico',
      atomic_mass: 74.9215956,
      boil: null,
      category: 'metaloide',
      color: null,
      density: 5.727,
      discovered_by: 'Bronze Age',
      melt: null,
      molar_heat: 24.64,
      named_by: null,
      number: 33,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Ars%C3%A9nico',
      spectral_img: null,
      summary:
        'El arsénico es un elemento químico de la tabla periódica que pertenece al grupo de los metaloides, también llamados semimetales; se puede encontrar de diversas formas aunque, raramente, se encuentra en estado sólido.',
      symbol: 'As',
      xpos: 15,
      ypos: 4,
      shells: [2, 8, 18, 5]
    },
    {
      name: 'Selenio',
      appearance: 'Gris metálico',
      atomic_mass: 78.9718,
      boil: 958,
      category: 'no metal poliatómico',
      color: null,
      density: 4.81,
      discovered_by: 'J\u00f6ns Jakob Berzelius',
      melt: 494,
      molar_heat: 25.363,
      named_by: null,
      number: 34,
      period: 4,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Selenio',
      spectral_img: null,
      summary:
        'El selenio es un elemento químico de la tabla periódica cuyo símbolo es Se y su número atómico 34. Pertenece a la familia de los no metales.',
      symbol: 'Se',
      xpos: 16,
      ypos: 4,
      shells: [2, 8, 18, 6]
    },
    {
      name: 'Bromo',
      appearance: 'Gas o líquido: marrón rojizo/ Sólido: metálico lustroso',
      atomic_mass: 79.904,
      boil: 332.0,
      category: 'no metal',
      color: null,
      density: 3.1028,
      discovered_by: 'Antoine J\u00e9r\u00f4me Balard',
      melt: 265.8,
      molar_heat: null,
      named_by: null,
      number: 35,
      period: 4,
      phase: 'Liquid',
      source: 'https://es.wikipedia.org/wiki/Bromo',
      spectral_img: null,
      summary:
        'El bromo es un elemento químico de número atómico 35 situado en el grupo de los halógenos (grupo VII A) de la tabla periódica de los elementos. Su símbolo es Br.',
      symbol: 'Br',
      xpos: 17,
      ypos: 4,
      shells: [2, 8, 18, 7]
    },
    {
      name: 'Krypton',
      appearance:
        'Incoloro',
      atomic_mass: 83.7982,
      boil: 119.93,
      category: 'gas noble',
      color: null,
      density: 3.749,
      discovered_by: 'William Ramsay',
      melt: 115.78,
      molar_heat: null,
      named_by: null,
      number: 36,
      period: 4,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Kript%C3%B3n',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Krypton_Spectrum.jpg',
      summary:
        'El kriptón o criptón es un elemento químico de la tabla periódica cuyo símbolo es Kr y su número atómico es 36.​ Es un gas noble incoloro, inodoro e insípido que se encuentra en cantidades mínimas en la atmósfera y es a menudo se utiliza con otros gases raros en lámparas fluorescentes.',
      symbol: 'Kr',
      xpos: 18,
      ypos: 4,
      shells: [2, 8, 18, 8]
    },
    {
      name: 'Rubidio',
      appearance: 'Plateado blanquecino',
      atomic_mass: 85.46783,
      boil: 961,
      category: 'metal alcalino',
      color: null,
      density: 1.532,
      discovered_by: 'Robert Bunsen',
      melt: 312.45,
      molar_heat: 31.06,
      named_by: null,
      number: 37,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Rubidio',
      spectral_img: null,
      summary:
        'El rubidio es un metal muy blando y de color blanco plateado del grupo de los metales alcalinos. El rubidio metálico comparte similitudes con el potasio y el cesio en cuanto a su aspecto físico, suavidad y conductividad.',
      symbol: 'Rb',
      xpos: 1,
      ypos: 5,
      shells: [2, 8, 18, 8, 1]
    },
    {
      name: 'Estroncio',
      appearance: 'Metálico plateado blanquecino',
      atomic_mass: 87.621,
      boil: 1650,
      category: 'metal alcalinotérreo',
      color: null,
      density: 2.64,
      discovered_by: 'William Cruickshank (chemist)',
      melt: 1050,
      molar_heat: 26.4,
      named_by: null,
      number: 38,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Estroncio',
      spectral_img: null,
      summary:
        'El estroncio es un metal blando de color plateado brillante, algo maleable, también alcalino térreo, que rápidamente se oxida en presencia de aire adquiriendo un tono amarillento por la formación de óxido, por lo que debe conservarse sumergido en parafina.',
      symbol: 'Sr',
      xpos: 2,
      ypos: 5,
      shells: [2, 8, 18, 8, 2]
    },
    {
      name: 'Itrio',
      appearance: 'Blanco plateado',
      atomic_mass: 88.905842,
      boil: 3203,
      category: 'metal de transición',
      color: null,
      density: 4.472,
      discovered_by: 'Johan Gadolin',
      melt: 1799,
      molar_heat: 26.53,
      named_by: null,
      number: 39,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Itrio',
      spectral_img: null,
      summary:
        'Es una tierra rara de transición del grupo IIIB. Es un metal plateado de transición, común en los minerales de tierras raras. Dos de sus compuestos se utilizan para hacer el color rojo de los diodos luminiscentes o ledes, usados en los visualizadores (como los televisores en color de rayos catódicos o CRT).',
      symbol: 'Y',
      xpos: 3,
      ypos: 5,
      shells: [2, 8, 18, 9, 2]
    },
    {
      name: 'Circonio',
      appearance: 'Blanco grisáceo',
      atomic_mass: 91.2242,
      boil: 4650,
      category: 'metal de transición',
      color: null,
      density: 6.52,
      discovered_by: 'Martin Heinrich Klaproth',
      melt: 2128,
      molar_heat: 25.36,
      named_by: null,
      number: 40,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Circonio',
      spectral_img: null,
      summary:
        'El circonio o zirconio es un elemento químico de número atómico 40 y peso atómico 91.224. Situado en el grupo 4 de la tabla periódica de los elementos. Su símbolo es Zr. El nombre de circonio se toma del mineral circón, la fuente más importante de circonio, y que deriva de la palabra persa "zargun - زرگون", que significa "dorado".',
      symbol: 'Zr',
      xpos: 4,
      ypos: 5,
      shells: [2, 8, 18, 10, 2]
    },
    {
      name: 'Niobio',
      appearance: 'Gris metálico',
      atomic_mass: 92.906372,
      boil: 5017,
      category: 'metal de transición',
      color: null,
      density: 8.57,
      discovered_by: 'Charles Hatchett',
      melt: 2750,
      molar_heat: 24.6,
      named_by: null,
      number: 41,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Niobio',
      spectral_img: null,
      summary:
        'El niobio es un elemento químico de número atómico 41 situado en el grupo 5 de la tabla periódica de los elementos. Se simboliza como Nb. Es un metal de transición dúctil, gris, blando y poco abundante. Se encuentra en el mineral niobita, también llamado columbita, y se utiliza en aleaciones.',
      symbol: 'Nb',
      xpos: 5,
      ypos: 5,
      shells: [2, 8, 18, 12, 1]
    },
    {
      name: 'Molibdeno',
      appearance: 'Gris metálico',
      atomic_mass: 95.951,
      boil: 4912,
      category: 'metal de transición',
      color: null,
      density: 10.28,
      discovered_by: 'Carl Wilhelm Scheele',
      melt: 2896,
      molar_heat: 24.06,
      named_by: null,
      number: 42,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Molibdeno',
      spectral_img: null,
      summary:
        'El molibdeno es un elemento químico de número atómico 42 que se encuentra en el grupo 6 de la tabla periódica de los elementos y se simboliza como Mo.',
      symbol: 'Mo',
      xpos: 6,
      ypos: 5,
      shells: [2, 8, 18, 13, 1]
    },
    {
      name: 'Tecnecio',
      appearance: 'Metálico plateado',
      atomic_mass: 98,
      boil: 4538,
      category: 'metal de transición',
      color: null,
      density: 11,
      discovered_by: 'Emilio Segr\u00e8',
      melt: 2430,
      molar_heat: 24.27,
      named_by: null,
      number: 43,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Tecnecio',
      spectral_img: null,
      summary:
        'El tecnecio es el más ligero de los elementos químicos que no cuentan con isótopos estables y el primer elemento sintético que se encuentra en la tabla periódica.',
      symbol: 'Tc',
      xpos: 7,
      ypos: 5,
      shells: [2, 8, 18, 13, 2]
    },
    {
      name: 'Rutenio',
      appearance: 'Blanco grisáceo',
      atomic_mass: 101.072,
      boil: 4423,
      category: 'metal de transición',
      color: null,
      density: 12.45,
      discovered_by: 'Karl Ernst Claus',
      melt: 2607,
      molar_heat: 24.06,
      named_by: null,
      number: 44,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Rutenio',
      spectral_img: null,
      summary:
        'El rutenio es un elemento químico de número atómico 44 situado en el grupo 8 de la tabla periódica de los elementos. Su símbolo es Ru. Es un metal de transición, poco abundante, del grupo del platino.',
      symbol: 'Ru',
      xpos: 8,
      ypos: 5,
      shells: [2, 8, 18, 15, 1]
    },
    {
      name: 'Rodio',
      appearance: 'Blanco plateado metálico',
      atomic_mass: 102.905502,
      boil: 3968,
      category: 'metal de transición',
      color: null,
      density: 12.41,
      discovered_by: 'William Hyde Wollaston',
      melt: 2237,
      molar_heat: 24.98,
      named_by: null,
      number: 45,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Rodio',
      spectral_img: null,
      summary:
        'El rodio es un elemento químico de número atómico 45 situado en el grupo 9 de la tabla periódica de los elementos. Su símbolo es Rh. Es un metal de transición, poco abundante, del grupo del platino. ',
      symbol: 'Rh',
      xpos: 9,
      ypos: 5,
      shells: [2, 8, 18, 16, 1]
    },
    {
      name: 'Paladio',
      appearance: 'Blanco plateado metálico',
      atomic_mass: 106.421,
      boil: 3236,
      category: 'metal de transición',
      color: null,
      density: 12.023,
      discovered_by: 'William Hyde Wollaston',
      melt: 1828.05,
      molar_heat: 25.98,
      named_by: null,
      number: 46,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Paladio',
      spectral_img: null,
      summary:
        'El paladio es un elemento químico de número atómico 46 situado en el grupo 10 de la tabla periódica de los elementos. Su símbolo es Pd. Es un metal de transición del grupo del platino, blando, dúctil, maleable y poco abundante. Se parece químicamente al platino y se extrae de algunas minas de cobre y níquel.',
      symbol: 'Pd',
      xpos: 10,
      ypos: 5,
      shells: [2, 8, 18, 18]
    },
    {
      name: 'Plata',
      appearance: 'Plateado',
      atomic_mass: 107.86822,
      boil: 2435,
      category: 'metal de transición',
      color: null,
      density: 10.49,
      discovered_by: 'unknown, before 5000 BC',
      melt: 1234.93,
      molar_heat: 25.35,
      named_by: null,
      number: 47,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Plata',
      spectral_img: null,
      summary:
        'La plata es un elemento químico de número atómico 47 situado en el grupo 11 de la tabla periódica de los elementos. Su símbolo es Ag (procede del latín argentum, “blanco”, “albo” o “brillante”). Es un metal noble, de transición, de color blanco brillante, blando, dúctil y maleable.',
      symbol: 'Ag',
      xpos: 11,
      ypos: 5,
      shells: [2, 8, 18, 18, 1]
    },
    {
      name: 'Cadmio',
      appearance: 'Plateado gris metálico',
      atomic_mass: 112.4144,
      boil: 1040,
      category: 'metal de transición',
      color: null,
      density: 8.65,
      discovered_by: 'Karl Samuel Leberecht Hermann',
      melt: 594.22,
      molar_heat: 26.02,
      named_by: 'Isotopes of cadmium',
      number: 48,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Cadmio',
      spectral_img: null,
      summary:
        'El cadmio es un elemento químico de número atómico 48 situado en el grupo 12 de la tabla periódica de los elementos. Su símbolo es Cd. Es un metal pesado, blando, blanco azulado, relativamente poco abundante. Es uno de los metales más tóxicos. Normalmente se encuentra en minas de zinc y se emplea especialmente en pilas.',
      symbol: 'Cd',
      xpos: 12,
      ypos: 5,
      shells: [2, 8, 18, 18, 2]
    },
    {
      name: 'Indio',
      appearance: 'Lustroso plateado grisáceo',
      atomic_mass: 114.8181,
      boil: 2345,
      category: 'metal de post transición',
      color: null,
      density: 7.31,
      discovered_by: 'Ferdinand Reich',
      melt: 429.7485,
      molar_heat: 26.74,
      named_by: null,
      number: 49,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Indio_(elemento)',
      spectral_img: null,
      summary:
        "El indio es un elemento químico de número atómico 49 situado en el grupo 13 y el período 5 de la tabla periódica de los elementos. Su símbolo es In. Es un metal poco abundante, maleable, fácilmente fundible, químicamente similar al aluminio y al galio, pero más parecido al zinc (de hecho, la principal fuente de obtención de este metal es a partir de los minerales de zinc).",
      symbol: 'In',
      xpos: 13,
      ypos: 5,
      shells: [2, 8, 18, 18, 3]
    },
    {
      name: 'Estaño',
      appearance: 'Gris plateado brillante',
      atomic_mass: 118.7107,
      boil: 2875,
      category: 'metal de post transición',
      color: null,
      density: 7.365,
      discovered_by: 'unknown, before 3500 BC',
      melt: 505.08,
      molar_heat: 27.112,
      named_by: null,
      number: 50,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Esta%C3%B1o',
      spectral_img: null,
      summary:
        'El estaño es un elemento químico de símbolo Sn (del latín stannum) y número atómico 50. Está situado en el grupo 14 de la tabla periódica de los elementos. Se conocen 10 isótopos estables. Su principal mena es la casiterita.',
      symbol: 'Sn',
      xpos: 14,
      ypos: 5,
      shells: [2, 8, 18, 18, 4]
    },
    {
      name: 'Antimonio',
      appearance: 'Gris plateado',
      atomic_mass: 121.7601,
      boil: 1908,
      category: 'metaloide',
      color: null,
      density: 6.697,
      discovered_by: 'unknown, before 3000 BC',
      melt: 903.78,
      molar_heat: 25.23,
      named_by: null,
      number: 51,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Antimonio',
      spectral_img: null,
      summary:
        'El antimonio es un elemento químico que forma parte del grupo de los metaloides de número atómico 51 situado en el grupo 15 de la tabla periódica de los elementos. Su nombre y abreviatura (Sb) procede de estibio, término hoy ya en desuso, que a su vez procede del latín stibium ("Banco de arena gris brillante").',
      symbol: 'Sb',
      xpos: 15,
      ypos: 5,
      shells: [2, 8, 18, 18, 5]
    },
    {
      name: 'Telurio',
      appearance: 'Gris plateado',
      atomic_mass: 127.603,
      boil: 1261,
      category: 'metaloide',
      color: null,
      density: 6.24,
      discovered_by: 'Franz-Joseph M\u00fcller von Reichenstein',
      melt: 722.66,
      molar_heat: 25.73,
      named_by: null,
      number: 52,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Telurio',
      spectral_img: null,
      summary:
        'El telurio o teluro​ (del latín tellus, Tierra) es un elemento químico cuyo símbolo es Te y su número atómico es 52. Es un semimetal que se encuentra en el grupo 16 y el periodo 5 de la Tabla periódica de los elementos.',
      symbol: 'Te',
      xpos: 16,
      ypos: 5,
      shells: [2, 8, 18, 18, 6]
    },
    {
      name: 'Yodo',
      appearance: '	Gris violáceo (Sólido)/ Violeta (Gas)/ Violeta (en disolvente apolar), naranja (en disolvente polar, formando poliyoduros).',
      atomic_mass: 126.904473,
      boil: 457.4,
      category: 'no metal',
      color: null,
      density: 4.933,
      discovered_by: 'Bernard Courtois',
      melt: 386.85,
      molar_heat: null,
      named_by: null,
      number: 53,
      period: 5,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Yodo',
      spectral_img: null,
      summary:
        'El yodo o iodo​ es un elemento químico de número atómico 53 situado en el grupo de los halógenos (grupo 17) de la tabla periódica de los elementos. Su símbolo es I (del griego ιώδης, iodes, "violeta"). Es un no metal debido a que no es un buen conductor del calor ni de la electricidad.',
      symbol: 'I',
      xpos: 17,
      ypos: 5,
      shells: [2, 8, 18, 18, 7]
    },
    {
      name: 'Xenón',
      appearance:
        'Incoloro',
      atomic_mass: 131.2936,
      boil: 165.051,
      category: 'gas noble',
      color: null,
      density: 5.894,
      discovered_by: 'William Ramsay',
      melt: 161.4,
      molar_heat: null,
      named_by: null,
      number: 54,
      period: 5,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Xen%C3%B3n',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Xenon_Spectrum.jpg',
      summary:
        "El xenón es un elemento químico de la tabla periódica cuyo símbolo es Xe y su número atómico el 54. Gas noble inodoro, muy pesado, incoloro, el xenón está presente en la atmósfera terrestre solo en trazas y fue parte del primer compuesto de gas noble sintetizado.",
      symbol: 'Xe',
      xpos: 18,
      ypos: 5,
      shells: [2, 8, 18, 18, 8]
    },
    {
      name: 'Cesio',
      appearance: 'Plateado-Dorado',
      atomic_mass: 132.905451966,
      boil: 944,
      category: 'metal alcalino',
      color: null,
      density: 1.93,
      discovered_by: 'Robert Bunsen',
      melt: 301.7,
      molar_heat: 32.21,
      named_by: null,
      number: 55,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Cesio',
      spectral_img: null,
      summary:
        'El cesio es el elemento químico con número atómico 55 y peso atómico de 132,905 u. Su símbolo es Cs, y es el más pesado de los metales alcalinos en el grupo IA de la tabla periódica, a excepción del francio (hasta febrero de 2007); se encuentra en componentes no orgánicos.',
      symbol: 'Cs',
      xpos: 1,
      ypos: 6,
      shells: [2, 8, 18, 18, 8, 1]
    },
    {
      name: 'Bario',
      appearance: 'Blanco plateado',
      atomic_mass: 137.3277,
      boil: 2118,
      category: 'metal alcalinotérreo',
      color: null,
      density: 3.51,
      discovered_by: 'Carl Wilhelm Scheele',
      melt: 1000,
      molar_heat: 28.07,
      named_by: null,
      number: 56,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Bario',
      spectral_img: null,
      summary:
        'El bario es un elemento químico de la tabla periódica cuyo símbolo es Ba y su número atómico es 56. Metal alcalinotérreo, el bario es el 18.º elemento más común, ocupando una parte de 2000 de la corteza terrestre. Su masa atómica es 137,34. Su punto de fusión está a 725 °C, su punto de ebullición a 1.640 °C, y su densidad relativa es 3,5. Su principal mena es la baritina.',
      symbol: 'Ba',
      xpos: 2,
      ypos: 6,
      shells: [2, 8, 18, 18, 8, 2]
    },
    {
      name: 'Lantano',
      appearance: 'Blanco plateado',
      atomic_mass: 138.905477,
      boil: 3737,
      category: 'lantánido',
      color: null,
      density: 6.162,
      discovered_by: 'Carl Gustaf Mosander',
      melt: 1193,
      molar_heat: 27.11,
      named_by: null,
      number: 57,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Lantano',
      spectral_img: null,
      summary:
        'El lantano es un elemento químico de la tabla periódica cuyo símbolo es La y su número atómico es 57. Es el primer elemento de la serie de los lantánidos.',
      symbol: 'La',
      xpos: 3,
      ypos: 9,
      shells: [2, 8, 18, 18, 9, 2]
    },
    {
      name: 'Cerio',
      appearance: 'Blanco plateado',
      atomic_mass: 140.1161,
      boil: 3716,
      category: 'lantánido',
      color: null,
      density: 6.77,
      discovered_by: 'Martin Heinrich Klaproth',
      melt: 1068,
      molar_heat: 26.94,
      named_by: null,
      number: 58,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Cerio',
      spectral_img: null,
      summary:
        'El cerio es un mineral y elemento químico de símbolo Ce y número atómico de 58. Es uno de los 14 elementos químicos que siguen al lantano en la tabla periódica, denominados por ello lantánidos.',
      symbol: 'Ce',
      xpos: 4,
      ypos: 9,
      shells: [2, 8, 18, 19, 9, 2]
    },
    {
      name: 'Praseodimio',
      appearance: 'Blanco plateado, amarillento',
      atomic_mass: 140.907662,
      boil: 3403,
      category: 'lantánido',
      color: null,
      density: 6.77,
      discovered_by: 'Carl Auer von Welsbach',
      melt: 1208,
      molar_heat: 27.2,
      named_by: null,
      number: 59,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Praseodimio',
      spectral_img: null,
      summary:
        'El praseodimio es un elemento químico de la tabla periódica cuyo símbolo es Pr y su número atómico es 59. Es parte del grupo de tierras raras. Fue descubierto en 1885 por el químico austríaco Carl Auer von Welsbach.',
      symbol: 'Pr',
      xpos: 5,
      ypos: 9,
      shells: [2, 8, 18, 21, 8, 2]
    },
    {
      name: 'Neodimio',
      appearance: 'Blanco plateado, amarillento',
      atomic_mass: 144.2423,
      boil: 3347,
      category: 'lantánido',
      color: null,
      density: 7.01,
      discovered_by: 'Carl Auer von Welsbach',
      melt: 1297,
      molar_heat: 27.45,
      named_by: null,
      number: 60,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Neodimio',
      spectral_img: null,
      summary:
        'El neodimio es un elemento químico cuyo símbolo es Nd y su número atómico es 60. A la temperatura ambiente, se encuentra en estado sólido. Es parte del grupo de tierras raras. Fue descubierto en 1885 por el químico austríaco Carl Auer von Welsbach.',
      symbol: 'Nd',
      xpos: 6,
      ypos: 9,
      shells: [2, 8, 18, 22, 8, 2]
    },
    {
      name: 'Prometio',
      appearance: 'metálico',
      atomic_mass: 145,
      boil: 3273,
      category: 'lantánido',
      color: null,
      density: 7.26,
      discovered_by: 'Chien Shiung Wu',
      melt: 1315,
      molar_heat: null,
      named_by: 'Isotopes of promethium',
      number: 61,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Prometio',
      spectral_img: null,
      summary:
        'El prometio es un elemento químico de la tabla periódica cuyo símbolo es Pm y su número atómico es 61. Algún tiempo se le denominó ilinio (por Illinois). Aunque, tras la observación de ciertas líneas espectrales, algunos científicos han reclamado haber descubierto este elemento en la naturaleza, nadie ha podido aislarlo de sustancias naturales.',
      symbol: 'Pm',
      xpos: 7,
      ypos: 9,
      shells: [2, 8, 18, 23, 8, 2]
    },
    {
      name: 'Samario',
      appearance: 'Blanco plateado',
      atomic_mass: 150.362,
      boil: 2173,
      category: 'lantánido',
      color: null,
      density: 7.52,
      discovered_by: 'Lecoq de Boisbaudran',
      melt: 1345,
      molar_heat: 29.54,
      named_by: null,
      number: 62,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Samario',
      spectral_img: null,
      summary:
        'El samario es un elemento químico de símbolo Sm y número atómico 62. Presenta una estructura cristalina romboedral, una masa atómica de 150,35 y una densidad de 7,35 g/cm³.',
      symbol: 'Sm',
      xpos: 8,
      ypos: 9,
      shells: [2, 8, 18, 24, 8, 2]
    },
    {
      name: 'Europio',
      appearance: null,
      atomic_mass: 151.9641,
      boil: 1802,
      category: 'lantánido',
      color: null,
      density: 5.264,
      discovered_by: 'Eug\u00e8ne-Anatole Demar\u00e7ay',
      melt: 1099,
      molar_heat: 27.66,
      named_by: null,
      number: 63,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Europio',
      spectral_img: null,
      summary:
        'El europio es un elemento químico de la tabla periódica cuyo símbolo es Eu y su número atómico es 63. Fue descubierto en 1890 por Paul Emile Lecoq de Boisbaudran y aislado por primera vez por Eugène Demarçay, quien le dio su actual nombre, en 1901. Debe su nombre al continente europeo.',
      symbol: 'Eu',
      xpos: 9,
      ypos: 9,
      shells: [2, 8, 18, 25, 8, 2]
    },
    {
      name: 'Gadolinio',
      appearance: 'Blanco plateado',
      atomic_mass: 157.253,
      boil: 3273,
      category: 'lantánido',
      color: null,
      density: 7.9,
      discovered_by: 'Jean Charles Galissard de Marignac',
      melt: 1585,
      molar_heat: 37.03,
      named_by: null,
      number: 64,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Gadolinio',
      spectral_img: null,
      summary:
        'El gadolinio es un elemento químico de la tabla periódica cuyo símbolo es Gd y cuyo número atómico es 64. Es un metal raro de color blanco plateado, es maleable y dúctil. Solo se encuentra en la naturaleza de forma combinada (sal).',
      symbol: 'Gd',
      xpos: 10,
      ypos: 9,
      shells: [2, 8, 18, 25, 9, 2]
    },
    {
      name: 'Terbio',
      appearance: 'Blanco plateado',
      atomic_mass: 158.925352,
      boil: 3396,
      category: 'lantánido',
      color: null,
      density: 8.23,
      discovered_by: 'Carl Gustaf Mosander',
      melt: 1629,
      molar_heat: 28.91,
      named_by: null,
      number: 65,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Terbio',
      spectral_img: null,
      summary:
        'El terbio es un elemento químico de la tabla periódica cuyo símbolo es Tb, sólido metálico de color blanco y brillo plateado. Su número atómico es 65, con una masa atómica de 158,9. Tiene una densidad de 8,3 g/cm³. Con un punto de fusión de 1.360 °C y un punto de ebullición de 3.041 °C. ',
      symbol: 'Tb',
      xpos: 11,
      ypos: 9,
      shells: [2, 8, 18, 27, 8, 2]
    },
    {
      name: 'Disprosio',
      appearance: 'blanco plateado',
      atomic_mass: 162.5001,
      boil: 2840,
      category: 'lantánido',
      color: null,
      density: 8.54,
      discovered_by: 'Lecoq de Boisbaudran',
      melt: 1680,
      molar_heat: 27.7,
      named_by: null,
      number: 66,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Disprosio',
      spectral_img: null,
      summary:
        'El disprosio es un elemento químico cuyo símbolo es Dy y su número atómico es 66. Es un metal de transición de color blanco plata, incluido en el grupo de los lantánidos o tierras raras. Fue identificado por primera vez en 1886 por Paul Émile Lecoq de Boisbaudran, pero no fue posible obtener una muestra pura hasta la década de 1950, con el método de intercambio iónico. ',
      symbol: 'Dy',
      xpos: 12,
      ypos: 9,
      shells: [2, 8, 18, 28, 8, 2]
    },
    {
      name: 'Holmio',
      appearance: 'Blanco plateado',
      atomic_mass: 164.930332,
      boil: 2873,
      category: 'lantánido',
      color: null,
      density: 8.79,
      discovered_by: 'Marc Delafontaine',
      melt: 1734,
      molar_heat: 27.15,
      named_by: null,
      number: 67,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Holmio',
      spectral_img: null,
      summary:
        'El holmio es un elemento químico cuyo nombre deriva del nombre en Latín de la ciudad de Estocolmo, Holmia. Fue descubierto por Marc Delafontaine y Jacques-Louis Soret, quienes en 1878 observaron las inusuales bandas de absorción espectrográficas de un elemento entonces desconocido.',
      symbol: 'Ho',
      xpos: 13,
      ypos: 9,
      shells: [2, 8, 18, 29, 8, 2]
    },
    {
      name: 'Erbio',
      appearance: 'Blanco plateado',
      atomic_mass: 167.2593,
      boil: 3141,
      category: 'lantánido',
      color: null,
      density: 9.066,
      discovered_by: 'Carl Gustaf Mosander',
      melt: 1802,
      molar_heat: 28.12,
      named_by: null,
      number: 68,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Erbio',
      spectral_img: null,
      summary:
        'El erbio es un elemento químico de la tabla periódica cuyo símbolo es Er y su número atómico es 68. El erbio es un elemento un tanto raro de color plateado perteneciente a los lantánidos y que aparece asociado a otros lantánidos en el mineral gadolinita procedente de Ytterby (Suecia).',
      symbol: 'Er',
      xpos: 14,
      ypos: 9,
      shells: [2, 8, 18, 30, 8, 2]
    },
    {
      name: 'Tulio',
      appearance: 'Gris plateado',
      atomic_mass: 168.934222,
      boil: 2223,
      category: 'lantánido',
      color: null,
      density: 9.32,
      discovered_by: 'Per Teodor Cleve',
      melt: 1818,
      molar_heat: 27.03,
      named_by: null,
      number: 69,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Tulio',
      spectral_img: null,
      summary:
        'Fue descubierto por Per Teodor Cleve en Suecia en el año 1879. Su nombre procede del antiguo nombre de Escandinavia en latín, Thule, ya que fue descubierto en esa región.',
      symbol: 'Tm',
      xpos: 15,
      ypos: 9,
      shells: [2, 8, 18, 31, 8, 2]
    },
    {
      name: 'Iterbio',
      appearance: 'Blanco plateado',
      atomic_mass: 173.0451,
      boil: 1469,
      category: 'lantánido',
      color: null,
      density: 6.9,
      discovered_by: 'Jean Charles Galissard de Marignac',
      melt: 1097,
      molar_heat: 26.74,
      named_by: null,
      number: 70,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Iterbio',
      spectral_img: null,
      summary:
        'El iterbio es un elemento químico de la tabla periódica que tiene el símbolo Yb y el número atómico 70. El iterbio es un elemento metálico plateado blando, una tierra rara de la serie de los lantánidos que se halla en la gadolinita, la monazita y el xenotimo. ',
      symbol: 'Yb',
      xpos: 16,
      ypos: 9,
      shells: [2, 8, 18, 32, 8, 2]
    },
    {
      name: 'Lutecio',
      appearance: 'Blanco plateado',
      atomic_mass: 174.96681,
      boil: 3675,
      category: 'lantánido',
      color: null,
      density: 9.841,
      discovered_by: 'Georges Urbain',
      melt: 1925,
      molar_heat: 26.86,
      named_by: null,
      number: 71,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Lutecio',
      spectral_img: null,
      summary:
        'El lutecio es un elemento químico, de número atómico 71, cuyo símbolo químico es Lu. A pesar de ser uno de los elementos del bloque d, con frecuencia aparece incluido entre los lantánidos (tierras raras), ya que con estos comparte muchas propiedades.',
      symbol: 'Lu',
      xpos: 17,
      ypos: 9,
      shells: [2, 8, 18, 32, 9, 2]
    },
    {
      name: 'Hafnio',
      appearance: 'Gris acero',
      atomic_mass: 178.492,
      boil: 4876,
      category: 'metal de transición',
      color: null,
      density: 13.31,
      discovered_by: 'Dirk Coster',
      melt: 2506,
      molar_heat: 25.73,
      named_by: null,
      number: 72,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Hafnio',
      spectral_img:
        'https://en.wikipedia.org/wiki/File:Hafnium_spectrum_visible.png',
      summary:
        'El hafnio es un elemento químico de número atómico 72 que se encuentra en el grupo 4 de la tabla periódica de los elementos y se simboliza como Hf.',
      symbol: 'Hf',
      xpos: 4,
      ypos: 6,
      shells: [2, 8, 18, 32, 10, 2]
    },
    {
      name: 'Tántalo ',
      appearance: 'Azul grisáceo',
      atomic_mass: 180.947882,
      boil: 5731,
      category: 'metal de transición',
      color: null,
      density: 16.69,
      discovered_by: 'Anders Gustaf Ekeberg',
      melt: 3290,
      molar_heat: 25.36,
      named_by: null,
      number: 73,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/T%C3%A1ntalo_(elemento)',
      spectral_img:
        'https://en.wikipedia.org/wiki/File:Tantalum_spectrum_visible.png',
      summary:
        'El tántalo,​ anteriormente también conocido como tantalio,​ es un elemento químico de número atómico 73, que se sitúa en el grupo 5 de la tabla periódica de los elementos. Su símbolo es Ta.',
      symbol: 'Ta',
      xpos: 5,
      ypos: 6,
      shells: [2, 8, 18, 32, 11, 2]
    },
    {
      name: 'Tungsteno',
      appearance: 'Gris brillante, Plateado',
      atomic_mass: 183.841,
      boil: 6203,
      category: 'metal de transición',
      color: null,
      density: 19.25,
      discovered_by: 'Carl Wilhelm Scheele',
      melt: 3695,
      molar_heat: 24.27,
      named_by: null,
      number: 74,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Wolframio',
      spectral_img: null,
      summary:
        'El wolframio o volframio, también conocido como wólfram​ o tungsteno, es un elemento químico de número atómico 74 que se encuentra en el grupo 6 de la tabla periódica de los elementos. Su símbolo es W. Es un metal escaso en la corteza terrestre, pero se encuentra en determinados minerales en forma de óxidos o sales.',
      symbol: 'W',
      xpos: 6,
      ypos: 6,
      shells: [2, 8, 18, 32, 12, 2]
    },
    {
      name: 'Renio',
      appearance: 'Blanco plateado',
      atomic_mass: 186.2071,
      boil: 5869,
      category: 'metal de transición',
      color: null,
      density: 21.02,
      discovered_by: 'Masataka Ogawa',
      melt: 3459,
      molar_heat: 25.48,
      named_by: 'Walter Noddack',
      number: 75,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Renio',
      spectral_img: null,
      summary:
        "El renio —de Rhenus, nombre latino del Rin— es un elemento químico, de número atómico 75, que se encuentra en el grupo 7 de la tabla periódica de los elementos y cuyo símbolo es Re, descubierto en 1925 por tres científicos alemanes. Es un metal de transición de color blanco-plata, sólido, refractario y resistente a la corrosión, muy utilizado en joyería y como catalizador.",
      symbol: 'Re',
      xpos: 7,
      ypos: 6,
      shells: [2, 8, 18, 32, 13, 2]
    },
    {
      name: 'Osmio',
      appearance: 'Azul grisáceo',
      atomic_mass: 190.233,
      boil: 5285,
      category: 'metal de transición',
      color: null,
      density: 22.59,
      discovered_by: 'Smithson Tennant',
      melt: 3306,
      molar_heat: 24.7,
      named_by: null,
      number: 76,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Osmio',
      spectral_img: null,
      summary:
        'Se trata de un metal de transición blanco grisáceo, frágil y sólido. Se clasifica dentro del grupo del platino, y se emplea en algunas aleaciones con platino e iridio. Se encuentra aleado en menas de platino y su tetróxido, OsO4.',
      symbol: 'Os',
      xpos: 8,
      ypos: 6,
      shells: [2, 8, 18, 32, 14, 2]
    },
    {
      name: 'Iridio',
      appearance: 'Blanco plateado',
      atomic_mass: 192.2173,
      boil: 4403,
      category: 'metal de transición',
      color: null,
      density: 22.56,
      discovered_by: 'Smithson Tennant',
      melt: 2719,
      molar_heat: 25.1,
      named_by: null,
      number: 77,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Iridio',
      spectral_img: null,
      summary:
        'El iridio es un elemento químico de número atómico 77 que se sitúa en el grupo 9 de la tabla periódica. Su símbolo es Ir. Se trata de un metal de transición, del grupo del platino, duro, frágil, pesado, de color blanco plateado. Es el segundo elemento más denso (después del osmio) y es el elemento más resistente a la corrosión, incluso a temperaturas tan altas como 2000 °C. ',
      symbol: 'Ir',
      xpos: 9,
      ypos: 6,
      shells: [2, 8, 18, 32, 15, 2]
    },
    {
      name: 'Platino',
      appearance: 'Blanco grisáceo',
      atomic_mass: 195.0849,
      boil: 4098,
      category: 'metal de transición',
      color: null,
      density: 21.45,
      discovered_by: 'Antonio de Ulloa',
      melt: 2041.4,
      molar_heat: 25.86,
      named_by: null,
      number: 78,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Platino',
      spectral_img: null,
      summary:
        'El platino es un elemento químico de número atómico 78, situado en el grupo 10 de la tabla periódica de los elementos. Su símbolo es Pt. Se trata de un metal de transición blanco grisáceo, precioso, pesado, maleable y dúctil. Es resistente a la corrosión y se encuentra en distintos minerales, frecuentemente junto con níquel y cobre; también se puede encontrar como metal.',
      symbol: 'Pt',
      xpos: 10,
      ypos: 6,
      shells: [2, 8, 18, 32, 17, 1]
    },
    {
      name: 'Oro',
      appearance: 'Amarillo metálico',
      atomic_mass: 196.9665695,
      boil: 3243,
      category: 'metal de transición',
      color: null,
      density: 19.3,
      discovered_by: 'Middle East',
      melt: 1337.33,
      molar_heat: 25.418,
      named_by: null,
      number: 79,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Oro',
      spectral_img: null,
      summary:
        'El oro es un elemento químico cuyo número atómico es 79. Está ubicado en el grupo 11 de la tabla periódica. Es un metal precioso blando de color amarillo dorado. Su símbolo es Au (del latín aurum, ‘brillante amanecer’). Además, es uno de los metales más apreciados en joyería por sus propiedades físicas, al tener baja alterabilidad, ser muy maleable, dúctil y brillante, y valorado por su rareza, al ser un metal difícil de encontrar en la naturaleza.',
      symbol: 'Au',
      xpos: 11,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 1]
    },
    {
      name: 'Mercurio',
      appearance: 'Blanco plateado',
      atomic_mass: 200.5923,
      boil: 629.88,
      category: 'metal de transición',
      color: null,
      density: 13.534,
      discovered_by: 'unknown, before 2000 BCE',
      melt: 234.321,
      molar_heat: 27.983,
      named_by: null,
      number: 80,
      period: 6,
      phase: 'Liquid',
      source: 'https://es.wikipedia.org/wiki/Mercurio_(elemento)',
      spectral_img: null,
      summary:
        'El mercurio es un elemento químico con el símbolo Hg y número atómico 80. En la literatura antigua era designado comúnmente como plata líquida y también como azogue o hidrargirio.',
      symbol: 'Hg',
      xpos: 12,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 2]
    },
    {
      name: 'Talio',
      appearance: 'Blanco plateado',
      atomic_mass: 204.38,
      boil: 1746,
      category: 'metal de post transición',
      color: null,
      density: 11.85,
      discovered_by: 'William Crookes',
      melt: 577,
      molar_heat: 26.32,
      named_by: null,
      number: 81,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Talio',
      spectral_img: null,
      summary:
        'El talio es un elemento químico de la tabla periódica cuyo símbolo es Tl y su número atómico es 81. Este metal del bloque p gris, blando y maleable es parecido al estaño, pero se decolora expuesto al aire. Es muy tóxico y se ha empleado como raticida e insecticida, pero este uso ha sido disminuido o eliminado en muchos países debido a sus posibles efectos cancerígenos. ',
      symbol: 'Tl',
      xpos: 13,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 3]
    },
    {
      name: 'Plomo',
      appearance: 'gris azulado',
      atomic_mass: 207.21,
      boil: 2022,
      category: 'metal de post transición',
      color: null,
      density: 11.34,
      discovered_by: 'Middle East',
      melt: 600.61,
      molar_heat: 26.65,
      named_by: null,
      number: 82,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Plomo',
      spectral_img: null,
      summary:
        'El plomo es un elemento químico de la tabla periódica, cuyo símbolo es Pb (del latín plumbum) y su número atómico es 82 según la tabla actual, ya que no formaba parte en la tabla periódica de Mendeléyev . ',
      symbol: 'Pb',
      xpos: 14,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 4]
    },
    {
      name: 'Bismuto',
      appearance: 'De color gris, ligeramente brillante.',
      atomic_mass: 208.980401,
      boil: 1837,
      category: 'metal de post transición',
      color: null,
      density: 9.78,
      discovered_by: 'Claude Fran\u00e7ois Geoffroy',
      melt: 544.7,
      molar_heat: 25.52,
      named_by: null,
      number: 83,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Bismuto',
      spectral_img: null,
      summary:
        'El bismuto es un elemento químico de la tabla periódica cuyo símbolo es Bi, su número atómico es 83 y se encuentra en el grupo 15 del sistema periódico.',
      symbol: 'Bi',
      xpos: 15,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 5]
    },
    {
      name: 'Polonio',
      appearance: 'Plateado',
      atomic_mass: 209,
      boil: 1235,
      category: 'metal de post transición',
      color: null,
      density: 9.196,
      discovered_by: 'Pierre Curie',
      melt: 527,
      molar_heat: 26.4,
      named_by: null,
      number: 84,
      period: 6,
      phase: 'Solid',
      source: 'https://en.wikipedia.org/wiki/Polonium',
      spectral_img: null,
      summary:
        'El polonio (latín: Polonium) es un elemento químico en la tabla periódica de los elementos cuyo símbolo es Po y su número atómico es 84. Se trata de un raro metal altamente radiactivo, químicamente similar al telurio y al bismuto, presente en minerales de uranio.',
      symbol: 'Po',
      xpos: 16,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 6]
    },
    {
      name: 'Ástato',
      appearance: 'Metálico',
      atomic_mass: 210,
      boil: 610,
      category: 'metaloide',
      color: null,
      density: 6.35,
      discovered_by: 'Dale R. Corson',
      melt: 575,
      molar_heat: null,
      named_by: null,
      number: 85,
      period: 6,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/%C3%81stato',
      spectral_img: null,
      summary:
        'El ástato o astato. Es un elemento químico de la tabla periódica cuyo símbolo es At y su número atómico es 85. Es radiactivo y el más pesado de los halógenos. Se produce a partir de la degradación de uranio y torio. Es el elemento más raro de la corteza terrestre, ya que sólo se encuentra en la cadena de desintegración de varios elementos más pesados.',
      symbol: 'At',
      xpos: 17,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 7]
    },
    {
      name: 'Radón',
      appearance:
        'Incoloro',
      atomic_mass: 222,
      boil: 211.5,
      category: 'gas noble',
      color: null,
      density: 9.73,
      discovered_by: 'Friedrich Ernst Dorn',
      melt: 202,
      molar_heat: null,
      named_by: null,
      number: 86,
      period: 6,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Rad%C3%B3n',
      spectral_img: 'https://en.wikipedia.org/wiki/File:Radon_spectrum.png',
      summary:
        'El radón es un elemento químico perteneciente al grupo de los gases nobles. En su forma gaseosa es incoloro, inodoro e insípido y en forma sólida su color es rojizo. En la tabla periódica tiene el número 86 y símbolo Rn. ',
      symbol: 'Rn',
      xpos: 18,
      ypos: 6,
      shells: [2, 8, 18, 32, 18, 8]
    },
    {
      name: 'Francio',
      appearance: 'Metálico',
      atomic_mass: 223,
      boil: 950,
      category: 'metal alcalino',
      color: null,
      density: 1.87,
      discovered_by: 'Marguerite Perey',
      melt: 300,
      molar_heat: null,
      named_by: null,
      number: 87,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Francio',
      spectral_img: null,
      summary:
        'El francio es un elemento químico cuyo símbolo es Fr y su número atómico es 87. Su electronegatividad es la más baja conocida y es el segundo elemento menos abundante en la naturaleza (el primero es el astato).',
      symbol: 'Fr',
      xpos: 1,
      ypos: 7,
      shells: [2, 8, 18, 32, 18, 8, 1]
    },
    {
      name: 'Radio',
      appearance: '	Plateado metálico blanquecino',
      atomic_mass: 226,
      boil: 2010,
      category: 'metal alcalinotérreo',
      color: null,
      density: 5.5,
      discovered_by: 'Pierre Curie',
      melt: 1233,
      molar_heat: null,
      named_by: null,
      number: 88,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Radio_(elemento)',
      spectral_img: null,
      summary:
        'El radio es un elemento químico de la tabla periódica. Su símbolo es Ra y su número atómico es 88.Es de color blanco inmaculado, pero se ennegrece con la exposición al aire. El radio es un alcalinotérreo que se encuentra a nivel de trazas en minas de uranio. ',
      symbol: 'Ra',
      xpos: 2,
      ypos: 7,
      shells: [2, 8, 18, 32, 18, 8, 2]
    },
    {
      name: 'Actinio',
      appearance: 'Plateado',
      atomic_mass: 227,
      boil: 3500,
      category: 'actínido',
      color: null,
      density: 10,
      discovered_by: 'Friedrich Oskar Giesel',
      melt: 1500,
      molar_heat: 27.2,
      named_by: null,
      number: 89,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Actinio',
      spectral_img: null,
      summary:
        'El actinio (del griego ακτις, ακτινoς, rayo luminoso) es un elemento químico de símbolo Ac y número atómico 89, perteneciente al grupo IIIB, periodo 7 y bloque D de la tabla periódica de los elementos.',
      symbol: 'Ac',
      xpos: 3,
      ypos: 10,
      shells: [2, 8, 18, 32, 18, 9, 2]
    },
    {
      name: 'Torio',
      appearance: 'Blanco plateado',
      atomic_mass: 232.03774,
      boil: 5061,
      category: 'actínido',
      color: null,
      density: 11.724,
      discovered_by: 'J\u00f6ns Jakob Berzelius',
      melt: 2023,
      molar_heat: 26.23,
      named_by: null,
      number: 90,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Torio',
      spectral_img: null,
      summary:
        'El torio es un elemento químico, de símbolo Th y número atómico 90, de la serie de los actínidos. Se encuentra en estado natural en los minerales monacita, torita y torianita. En estado puro es un metal blando de color blanco-plata que se oxida lentamente. Si se tritura finamente y se calienta, arde y emite luz blanca.',
      symbol: 'Th',
      xpos: 4,
      ypos: 10,
      shells: [2, 8, 18, 32, 18, 10, 2]
    },
    {
      name: 'Protactinio',
      appearance: 'Blanco plateado brillante',
      atomic_mass: 231.035882,
      boil: 4300,
      category: 'actínido',
      color: null,
      density: 15.37,
      discovered_by: 'William Crookes',
      melt: 1841,
      molar_heat: null,
      named_by: 'Otto Hahn',
      number: 91,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Protactinio',
      spectral_img: null,
      summary:
        'El protactinio es un elemento metálico plateado que pertenece al grupo de los actínidos, que presenta un brillo metálico intenso. Es superconductor por debajo de 1.4 K.',
      symbol: 'Pa',
      xpos: 5,
      ypos: 10,
      shells: [2, 8, 18, 32, 20, 9, 2]
    },
    {
      name: 'Uranio',
      appearance: 'Metal blanco plateado',
      atomic_mass: 238.028913,
      boil: 4404,
      category: 'actínido',
      color: null,
      density: 19.1,
      discovered_by: 'Martin Heinrich Klaproth',
      melt: 1405.3,
      molar_heat: 27.665,
      named_by: null,
      number: 92,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Uranio',
      spectral_img: null,
      summary:
        'El uranio es un elemento químico metálico de color plateado-grisáceo de la serie de los actínidos, su símbolo químico es U y su número atómico es 92. Por ello posee 92 protones y 92 electrones, con una valencia de 6.',
      symbol: 'U',
      xpos: 6,
      ypos: 10,
      shells: [2, 8, 18, 32, 21, 9, 2]
    },
    {
      name: 'Neptunio',
      appearance: 'Plateado metálico',
      atomic_mass: 237,
      boil: 4447,
      category: 'actínido',
      color: null,
      density: 20.45,
      discovered_by: 'Edwin McMillan',
      melt: 912,
      molar_heat: 29.46,
      named_by: null,
      number: 93,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Neptunio',
      spectral_img: null,
      summary:
        'El neptunio es un elemento transuránico de la tabla periódica cuyo símbolo es Np y su número atómico es 93. Cuarto de la familia de los actínidos o segundo período de transición interna del sistema periódico de los elementos. Su nombre proviene del planeta Neptuno.',
      symbol: 'Np',
      xpos: 7,
      ypos: 10,
      shells: [2, 8, 18, 32, 22, 9, 2]
    },
    {
      name: 'Plutonio',
      appearance: 'Blanco plateado',
      atomic_mass: 244,
      boil: 3505,
      category: 'actínido',
      color: null,
      density: 19.816,
      discovered_by: 'Glenn T. Seaborg',
      melt: 912.5,
      molar_heat: 35.5,
      named_by: null,
      number: 94,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Plutonio',
      spectral_img: null,
      summary:
        'El plutonio es un elemento transuránico radiactivo con el símbolo químico Pu y el número atómico 94. Es un metal actínido con apariencia gris plateada que se oscurece cuando es expuesto al aire, formando una capa opaca cuando se oxida.',
      symbol: 'Pu',
      xpos: 8,
      ypos: 10,
      shells: [2, 8, 18, 32, 24, 8, 2]
    },
    {
      name: 'Americio',
      appearance: 'Blanco/plateado',
      atomic_mass: 243,
      boil: 2880,
      category: 'actínido',
      color: null,
      density: 12,
      discovered_by: 'Glenn T. Seaborg',
      melt: 1449,
      molar_heat: 62.7,
      named_by: null,
      number: 95,
      period: 7,
      phase: 'Solid',
      source: 'https://en.wikipedia.org/wiki/Americium',
      spectral_img:
        'https://en.wikipedia.org/wiki/File:Americium_spectrum_visible.png',
      summary:
        'El americio es un elemento químico artificial de número atómico 95 situado dentro del grupo de los actínidos en la tabla periódica de los elementos. Su símbolo es Am.',
      symbol: 'Am',
      xpos: 9,
      ypos: 10,
      shells: [2, 8, 18, 32, 25, 8, 2]
    },
    {
      name: 'Curio',
      appearance: 'Plateado',
      atomic_mass: 247,
      boil: 3383,
      category: 'actínido',
      color: null,
      density: 13.51,
      discovered_by: 'Glenn T. Seaborg',
      melt: 1613,
      molar_heat: null,
      named_by: null,
      number: 96,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Curio',
      spectral_img: null,
      summary:
        'El curio es un elemento sintético de la tabla periódica cuyo símbolo es Cm y su número atómico es 96. Se produce bombardeando plutonio con partículas alfa (iones de helio).',
      symbol: 'Cm',
      xpos: 10,
      ypos: 10,
      shells: [2, 8, 18, 32, 25, 9, 2]
    },
    {
      name: 'Berkelio',
      appearance: 'Blanco frágil',
      atomic_mass: 247,
      boil: 2900,
      category: 'actínido',
      color: null,
      density: 14.78,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: 1259,
      molar_heat: null,
      named_by: null,
      number: 97,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Berkelio',
      spectral_img: null,
      summary:
        'El berkelio es un elemento sintético de la tabla periódica cuyo símbolo es el Bk y su número atómico es 97. Pertenece a la serie de los actínidos y elementos transuránicos.',
      symbol: 'Bk',
      xpos: 11,
      ypos: 10,
      shells: [2, 8, 18, 32, 27, 8, 2]
    },
    {
      name: 'Californio',
      appearance: 'Un pequeño disco de californio ampliado para ver su textura metálica',
      atomic_mass: 251,
      boil: 1743,
      category: 'actínido',
      color: null,
      density: 15.1,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: 1173,
      molar_heat: null,
      named_by: null,
      number: 98,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Californio',
      spectral_img: null,
      summary:
        'El californio es un elemento químico radiactivo con símbolo Cf y número atómico 98. Este elemento fue obtenido por primera vez en la Universidad de California en Berkeley.',
      symbol: 'Cf',
      xpos: 12,
      ypos: 10,
      shells: [2, 8, 18, 32, 28, 8, 2]
    },
    {
      name: 'Einstenio',
      appearance: '	Desconocida. Probablemente metálico, plateado blanco o gris',
      atomic_mass: 252,
      boil: 1269,
      category: 'actínido',
      color: null,
      density: 8.84,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: 1133,
      molar_heat: null,
      named_by: null,
      number: 99,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Einstenio',
      spectral_img: null,
      summary:
        'El einstenio es un elemento sintético de la tabla periódica cuyo símbolo es Es y su número atómico es 99. Fue llamado así en honor de Albert Einstein, aunque se descubrió en diciembre de 1952 en los restos de la primera explosión termonuclear en el Pacífico, realizada un mes antes.',
      symbol: 'Es',
      xpos: 13,
      ypos: 10,
      shells: [2, 8, 18, 32, 29, 8, 2]
    },
    {
      name: 'Fermio',
      appearance: null,
      atomic_mass: 257,
      boil: null,
      category: 'actínido',
      color: null,
      density: null,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: 1800,
      molar_heat: null,
      named_by: null,
      number: 100,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Fermio',
      spectral_img: null,
      summary:
        'El fermio es un elemento químico radiactivo creado artificialmente cuyo número atómico es 100 y de peso atómico 254, de símbolo Fm. Existen 16 isótopos conocidos siendo el 257Fm el más estable con un periodo de semidesintegración de 100,5 días.',
      symbol: 'Fm',
      xpos: 14,
      ypos: 10,
      shells: [2, 8, 18, 32, 30, 8, 2]
    },
    {
      name: 'Mendelevio',
      appearance: 'Desconocida. Probablemente metálico, plateado blanco o gris',
      atomic_mass: 258,
      boil: null,
      category: 'actínido',
      color: null,
      density: null,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: 1100,
      molar_heat: null,
      named_by: null,
      number: 101,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Mendelevio',
      spectral_img: null,
      summary:
        'El mendelevio es un elemento de la tabla periódica cuyo símbolo es Md (anteriormente Mv) y su número atómico es 101. El nombre de este elemento proviene del creador de la tabla periódica de los elementos: Dmitri Mendeleyev (1834-1907).',
      symbol: 'Md',
      xpos: 15,
      ypos: 10,
      shells: [2, 8, 18, 32, 31, 8, 2]
    },
    {
      name: 'Nobelio',
      appearance: 'Desconocida',
      atomic_mass: 259,
      boil: null,
      category: 'actínido',
      color: null,
      density: null,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: 1100,
      molar_heat: null,
      named_by: null,
      number: 102,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Nobelio',
      spectral_img: null,
      summary:
        'El nobelio es un elemento sintético de la tabla periódica cuyo símbolo es No y su número atómico es 102, llamado así en honor del inventor Alfred Nobel. Es el 11º elemento sintético de la tabla periódica.',
      symbol: 'No',
      xpos: 16,
      ypos: 10,
      shells: [2, 8, 18, 32, 32, 8, 2]
    },
    {
      name: 'Lawrencio',
      appearance: null,
      atomic_mass: 266,
      boil: null,
      category: 'actínido',
      color: null,
      density: null,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: 1900,
      molar_heat: null,
      named_by: null,
      number: 103,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Lawrencio',
      spectral_img: null,
      summary:
        'El lawrencio o laurencio es un elemento sintético radiactivo de la tabla periódica de los elementos cuyo símbolo es Lr (anteriormente Lw) y su número atómico es 103.',
      symbol: 'Lr',
      xpos: 17,
      ypos: 10,
      shells: [2, 8, 18, 32, 32, 8, 3]
    },
    {
      name: 'Rutherfordio',
      appearance: null,
      atomic_mass: 267,
      boil: 5800,
      category: 'metal de transición',
      color: null,
      density: 23.2,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: 2400,
      molar_heat: null,
      named_by: null,
      number: 104,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Rutherfordio',
      spectral_img: null,
      summary:
        'El rutherfordio (anteriormente llamado kurchatovio) es un elemento químico de la tabla periódica cuyo símbolo es Rf y su número atómico es 104. Su nombre fue elegido en honor del Barón Ernest Rutherford, científico colaborador del modelo atómico y física nuclear.',
      symbol: 'Rf',
      xpos: 4,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 10, 2]
    },
    {
      name: 'Dubnio',
      appearance: 'Desconocido; probablemente metálico plateado blanco o gris',
      atomic_mass: 268,
      boil: null,
      category: 'metal de transición',
      color: null,
      density: 29.3,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 105,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Dubnio',
      spectral_img: null,
      summary:
        'El dubnio es un elemento químico de la tabla periódica de los elementos cuyo símbolo es Db y su número atómico 105. El elemento fue nombrado en honor a la ciudad de Dubná, Rusia, sede del Instituto Central de Investigaciones Nucleares, donde fue producido por primera vez. ',
      symbol: 'Db',
      xpos: 5,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 11, 2]
    },
    {
      name: 'Seaborgio',
      appearance: 'Desconocida',
      atomic_mass: 269,
      boil: null,
      category: 'metal de transición',
      color: null,
      density: 35.0,
      discovered_by: 'Lawrence Berkeley National Laboratory',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 106,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Seaborgio',
      spectral_img: null,
      summary:
        'El seaborgio es un elemento químico de la tabla periódica cuyo símbolo es Sg y su número atómico es 106. Es un elemento sintético cuyo isótopo más estable es el 271Sg que tiene una vida media de 2,4 minutos. Su naturaleza química es similar a la del wolframio.',
      symbol: 'Sg',
      xpos: 6,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 12, 2]
    },
    {
      name: 'Bohrio',
      appearance: null,
      atomic_mass: 270,
      boil: null,
      category: 'metal de transición',
      color: null,
      density: 37.1,
      discovered_by: 'Gesellschaft f\u00fcr Schwerionenforschung',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 107,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Bohrio',
      spectral_img: null,
      summary:
        'El bohrio es un elemento químico de la tabla periódica cuyo símbolo es Bh y su número atómico es 107. Su nombre le fue dado en honor al científico danés Niels Bohr.',
      symbol: 'Bh',
      xpos: 7,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 13, 2]
    },
    {
      name: 'Hasio',
      appearance: 'Desconocida',
      atomic_mass: 269,
      boil: null,
      category: 'metal de transición',
      color: null,
      density: 40.7,
      discovered_by: 'Gesellschaft f\u00fcr Schwerionenforschung',
      melt: 126,
      molar_heat: null,
      named_by: null,
      number: 108,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Hasio',
      spectral_img: null,
      summary:
        'El hasio es un elemento sintético de la tabla periódica cuyo símbolo es Hs y su número atómico es 108. Su isótopo más estable es el Hs-269, que tiene un periodo de semidesintegración de 9,7 segundos.',
      symbol: 'Hs',
      xpos: 8,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 14, 2]
    },
    {
      name: 'Meitnerio',
      appearance: 'Desconocida',
      atomic_mass: 278,
      boil: null,
      category: 'desconocido',
      color: null,
      density: 37.4,
      discovered_by: 'Gesellschaft f\u00fcr Schwerionenforschung',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 109,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Meitnerio',
      spectral_img: null,
      summary:
        'El meitnerio es un elemento químico de la tabla periódica cuyo símbolo es Mt y su número atómico es 109. Es un elemento sintético cuyo isótopo más estable es el 278Mt, cuya vida media es de 7,6 s.',
      symbol: 'Mt',
      xpos: 9,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 15, 2]
    },
    {
      name: 'Darmstatio',
      appearance: 'Desconocida',
      atomic_mass: 281,
      boil: null,
      category: 'desconocido',
      color: null,
      density: 34.8,
      discovered_by: 'Gesellschaft f\u00fcr Schwerionenforschung',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 110,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Darmstatio',
      spectral_img: null,
      summary:
        'El darmstatio o darmstadtio​ es un elemento químico de la tabla periódica cuyo símbolo es Ds y cuyo número atómico es 110, lo cual lo hace uno de los átomos superpesados.',
      symbol: 'Ds',
      xpos: 10,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 16, 2]
    },
    {
      name: 'Roentgenio',
      appearance: 'Desconocida',
      atomic_mass: 282,
      boil: null,
      category: 'desconocido',
      color: null,
      density: 28.7,
      discovered_by: 'Gesellschaft f\u00fcr Schwerionenforschung',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 111,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Roentgenio',
      spectral_img: null,
      summary:
        'El roentgenio es un elemento químico del grupo 11 de la tabla periódica cuyo símbolo es Rg y su número atómico es 111.',
      symbol: 'Rg',
      xpos: 11,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 17, 2]
    },
    {
      name: 'Copernicio',
      appearance: null,
      atomic_mass: 285,
      boil: 3570,
      category: 'metal de transición',
      color: null,
      density: 23.7,
      discovered_by: 'Gesellschaft f\u00fcr Schwerionenforschung',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 112,
      period: 7,
      phase: 'Gas',
      source: 'https://es.wikipedia.org/wiki/Copernicio',
      spectral_img: null,
      summary:
        'El copernicio es un elemento químico de la tabla periódica cuyo símbolo es Cn y su número atómico 112. Su apariencia física no se conoce aún, pero podría calcularse, sabiendo que por ahora el isótopo conocido, de 285 de masa atómica, tiene una vida media de 0,24 ms.',
      symbol: 'Cn',
      xpos: 12,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 2]
    },
    {
      name: 'Nihonio',
      appearance: null,
      atomic_mass: 286,
      boil: 1430,
      category: 'desconocido',
      color: null,
      density: 16,
      discovered_by: 'RIKEN',
      melt: 700,
      molar_heat: null,
      named_by: null,
      number: 113,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Nihonio',
      spectral_img: null,
      summary:
        'Su descubrimiento ha sido adjudicado de forma oficial a los investigadores japoneses del laboratorio Riken, que lograron sintetizar y observar el elemento a finales de 2015, convirtiéndose así en el primer elemento sintético en ser producido en Japón.',
      symbol: 'Nh',
      xpos: 13,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 3]
    },
    {
      name: 'Flerovio',
      appearance: 'Desconocida',
      atomic_mass: 289,
      boil: 420,
      category: 'metal de post transición',
      color: null,
      density: 14,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: 340,
      molar_heat: null,
      named_by: null,
      number: 114,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Flerovio',
      spectral_img: null,
      summary:
        'Flerovio es el nombre de un elemento químico radiactivo con el símbolo Fl y número atómico 114. Nombrado en honor a Gueorgui Fliórov.',
      symbol: 'Fl',
      xpos: 14,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 4]
    },
    {
      name: 'Moscovio',
      appearance: 'Desconocida',
      atomic_mass: 289,
      boil: 1400,
      category: 'desconocido',
      color: null,
      density: 13.5,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: 670,
      molar_heat: null,
      named_by: null,
      number: 115,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Moscovio',
      spectral_img: null,
      summary:
        'El moscovio​ es un elemento sintético de la tabla periódica cuyo símbolo es Mc y su número atómico es 115.',
      symbol: 'Mc',
      xpos: 15,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 5]
    },
    {
      name: 'Livermorio',
      appearance: null,
      atomic_mass: 293,
      boil: 1085,
      category: 'desconocido',
      color: null,
      density: 12.9,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: 709,
      molar_heat: null,
      named_by: null,
      number: 116,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Livermorio',
      spectral_img: null,
      summary:
        'El livermorio es el nombre del elemento sintético de la tabla periódica cuyo símbolo es Lv y su número atómico es 116.',
      symbol: 'Lv',
      xpos: 16,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 6]
    },
    {
      name: 'Teneso',
      appearance: 'Desconocida',
      atomic_mass: 294,
      boil: 883,
      category: 'desconocido',
      color: null,
      density: 7.17,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: 723,
      molar_heat: null,
      named_by: null,
      number: 117,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Teneso',
      spectral_img: null,
      summary:
        'El teneso es un elemento sintético muy pesado de la tabla periódica de los elementos cuyo símbolo es Ts y número atómico 117. También conocido como eka-astato o simplemente elemento 117, es el segundo elemento más pesado creado hasta ahora y el penúltimo del séptimo período en la tabla periódica.',
      symbol: 'Ts',
      xpos: 17,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 7]
    },
    {
      name: 'Oganesón',
      appearance: 'Desconocida',
      atomic_mass: 294,
      boil: 350,
      category: 'desconocido',
      color: null,
      density: 4.95,
      discovered_by: 'Joint Institute for Nuclear Research',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 118,
      period: 7,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Oganes%C3%B3n',
      spectral_img: null,
      summary:
        "El oganesón es el nombre para el elemento sintético de la tabla periódica cuyo símbolo es Og y su número atómico es 118.​ Es el elemento más pesado sintetizado hasta ahora y el último del séptimo período en la tabla periódica.",
      symbol: 'Og',
      xpos: 18,
      ypos: 7,
      shells: [2, 8, 18, 32, 32, 18, 8]
    },
    {
      name: 'Ununennio',
      appearance: null,
      atomic_mass: 315,
      boil: 630,
      category: 'desconocido',
      color: null,
      density: 3,
      discovered_by: 'GSI Helmholtz Centre for Heavy Ion Research',
      melt: null,
      molar_heat: null,
      named_by: null,
      number: 119,
      period: 8,
      phase: 'Solid',
      source: 'https://es.wikipedia.org/wiki/Ununennio',
      spectral_img: null,
      summary:
        'Ununennio, también conocido como eka-francio, es el hipotético elemento químico con los símbolos Uue (aceptables) y de número atómico 119. En la tabla periódica se localiza en el segmento de los metales alcalinos, y es el primer elemento en el octavo período. Es el elemento más ligero que aún no ha sido sintetizado.',
      symbol: 'Uue',
      xpos: 1,
      ypos: 8,
      shells: [2, 8, 18, 32, 32, 18, 8, 1]
    }
  ]
};
